[package]
name = "tx3-build"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.98"
tx3-lang = { path = "../tx3-lang" }
tx3-vm = { version = "0.1.0", path = "../tx3-vm" }
